const OrdersActionTypes = {
  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
  SET_ORDER_START: 'SET_ORDER_START',
  SET_ORDER_SUCCESS: 'SET_ORDER_SUCCESS',
  SET_ORDER_FAILURE: 'SET_ORDER_FAILURE',
  SET_ORDER_IS_LOADING: 'SET_ORDER_IS_LOADING'
};

export default OrdersActionTypes;